Bug - teamcenter-sync continues if target not mounted
A series of events led to some surprising discoveries:

    - puppet stopped running on tc-util after the CA certificate expired
      because the tc-util certificate never got signed by the new CA

    - because puppet wasn't running it was possible for remote file
      systems to become unmounted and stay that way

    - because the remote file systems were unmounted a TARGET would
      ultimately be just the root filesystem which meant:

        - the real TARGET did not actually get updated

        - the root file system free space would be effectively exhausted
          completely

The script has been revised to abort if either the SOURCE or TARGET
remote file systems are not mounted.  In the case of TARGET, this
prevents the situation described above.  In the unseen case of SOURCE,
this prevents something much worse -- synchronizing an empty directory
to an otherwise good TARGET.

diff --git a/modules/dart/templates/tc_util/teamcenter-sync b/modules/dart/templates/tc_util/teamcenter-sync
--- a/modules/dart/templates/tc_util/teamcenter-sync
+++ b/modules/dart/templates/tc_util/teamcenter-sync
@@ -47,6 +47,15 @@ warn() {
     echo >&2 "WARNING: $@"
 }
 
+mounted() {
+    # Test a mount point to determine something is mounted there or not.
+    #
+    # @1:       Mount point to be tested.
+    # @returns: 0 iff mounted; not 0 otherwise.
+    what="$(readlink -f $1)"
+    grep -q "$what" /proc/mounts
+}
+
 # Note: Trailing slash is critical and must be present!
 SOURCE='/srv/<%= sync_source %>-volumes/'
 TARGET=''
@@ -85,6 +94,12 @@ do
 done
 [ $# -eq 0 ] || warn "ignoring unexpected arguments: $@"
 [ -n "$TARGET" ] || fail "missing required argument: TARGET"
+
+mounted "$SOURCE" \
+    || fail "Cannot continue because SOURCE '${SOURCE}' is not mounted."
+
+mounted "$TARGET" \
+    || fail "Cannot continue because TARGET '${TARGET}' is not mounted."
 
 # Establish a crude real-time log monitor to provide immediate feedback of
 # progress (and errors) to the user.
